export default [
  { title: 'Data Science: R Basics', price: 49 },
  { title: 'Data Science: Probability', price: 49 },
  { title: 'Data Science: Machine Learning', price: 49 },
  { title: 'Foundations of Data Science: Computational Thinking with Python', price: 99 },
  { title: 'Data Science: Wrangling', price: 49 },
  { title: 'Statistical Thinking for Data Science and Analytics', price: 99 },
  { title: 'Best Practices for Project Management Success', price: 150 },
  { title: 'Project Management Life Cycle', price: 150 },
  { title: 'Leadership and Management for PM Practitioners in IT', price: 99 },
  { title: 'Business Analytics for Data-Driven Decision Making', price: 200 },
  { title: 'Reputation Management in a Digital World', price: 99 },
  { title: 'Strategic Brand Management', price: 199 },
  { title: 'Artificial Intelligence (AI)', price: 199 },
  { title: 'Machine Learning', price: 199 },
  { title: 'Robotics', price: 249 },
  { title: 'Deep Learning with Python and PyTorch', price: 99 },
  { title: 'Introduction to Artificial Intelligence (AI)', price: 99 },
  { title: 'Design Thinking: Empathizing to Understand the Problem', price: 200 },
  { title: 'Product Management with Lean, Agile and System Design Thinking', price: 200 },
  { title: 'Platform Strategy for Business', price: 200 },
  { title: 'Business Analytics for Data-Driven Decision Making', price: 200 },
  { title: 'Understanding User Needs', price: 99 },
  { title: 'Introduction to the Internet of Things (IoT)', price: 99 },
  { title: 'Azure Security and Compliance', price: 99 },
  { title: 'Cloud Computing for Enterprises', price: 249 },
  { title: 'Network Security', price: 150 },
  { title: 'Business Communication', price: 49 },
  { title: 'Teamwork & Collaboration', price: 49 },
  { title: 'Critical Thinking & Problem-Solving', price: 49 },
  { title: 'Storytelling in the Workplace', price: 49 },
  { title: 'Public Speaking', price: 49 },
  { title: 'Visual Presentation', price: 49 },
  { title: 'Analyzing and Visualizing Data with Excel', price: 99 },
  { title: 'Business Writing', price: 267.30 },
  { title: 'Leadership and Influence', price: 214 },
  { title: 'Management in Engineering I', price: 175 },
  { title: 'Introduction to FinTech', price: 99 },
  { title: 'Introduction to Computing in Python', price: 270 },
  { title: 'CS50\'s Introduction to Computer Science', price: 90 },
  { title: 'u.lab: Leading Change in Times of Disruption', price: 49 },
  { title: 'Blockchain Technology', price: 99 },
  { title: 'Bitcoin and Cryptocurrencies', price: 99 },
  { title: 'Becoming a Successful Leader (Inclusive Leadership Training)', price: 50 },
  { title: 'Leading With Effective Communication (Inclusive Leadership Training)', price: 50 },
  { title: 'Algorithmic Design and Techniques', price: 150 },
  { title: 'Data Structures Fundamentals', price: 150 },
  { title: 'Empathy and Emotional Intelligence at Work', price: 149 },
  { title: 'Six Sigma: Define and Measure', price: 88 },
  { title: 'Lean Production', price: 88 },
];
